title: BigText
description: Looking at how type is used in gigantic lettering
header_text: Giant text
footer_text: Copyright 2020 Chris jennings
header_feature_image: ../uploads/bigtext.jpg
logo: ../uploads/btlogo.png
favicon: /uploads/favicon.ico
gridlayout: false
bannerheight: "50"
upzoom: true
