title: BigText
description: Looking at how type is used in gigantic lettering
header_text: ""
footer_text: Copyright 2020 Chris jennings
header_feature_image: ../uploads/bigtext.jpg
bannerheight: "20"
logo: ../uploads/btlogo.png
favicon: /uploads/favicon.ico
gridlayout: false
upzoom: true
